trigger: none


pool:
  name: Azure_Project_VM

variables:
  SONARQUBE_HOST_URL: "http://52.234.35.11:9000"
  SONARQUBE_TOKEN: squ_437664680ac09398422b376153585e3d2efd5a86
steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
- task: SonarQubePrepare@7
  inputs:
    SonarQube: 'Sonar-AZD'
    scannerMode: 'cli'
    configMode: 'manual'
    cliProjectKey: 'Test-Sonar'
    cliProjectName: 'Test-Java-Sonar'
    cliSources: '.'
    extraProperties: |
      # Additional properties that will be passed to the scanner, 
      # Put one key=value per line, example:
      # sonar.exclusions=**/*.bin
      sonar.java.binaries=.

# Run the scanner manually to bypass Azure DevOps branch injection
- script: |
    echo "Running SonarQube scanner manually..."
    /opt/sonar-scanner-4.8.0.2856-linux/bin/sonar-scanner \
      -Dsonar.sources=. \
      -Dsonar.host.url=$(SONARQUBE_HOST_URL) \
      -Dsonar.login=$(SONARQUBE_TOKEN)
  displayName: 'Run SonarQube Scanner Manually'
- task: SonarQubePublish@7
  inputs:
    pollingTimeoutSec: '300'