trigger: none

pool:
  name: Azure_Project_VM

variables:
  SONARQUBE_HOST_URL: "http://52.234.35.11:9000"
  SONARQUBE_TOKEN: squ_437664680ac09398422b376153585e3d2efd5a86
  SONAR_PROJECT_KEY: "Test-Sonar-$(Build.BuildId)"
  SONAR_PROJECT_NAME: "Test-Java-Sonar-$(Build.BuildId)"

steps:
- task: SonarQubePrepare@7
  inputs:
    SonarQube: 'Sonar-AZD'
    scannerMode: 'Other'
    configMode: 'manual'
    cliProjectKey: Test-Sonar-$(Build.BuildId)
    cliProjectName: Test-Java-Sonar-$(Build.BuildId)
    cliSources: '.'

- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'package sonar:sonar'

- task: SonarQubePublish@7
  inputs:
    pollingTimeoutSec: '300'
