trigger: none

variables:
  ACR_NAME: myacrkrishnakiran2
  AKS_RG: krishna-kiran
  AKS_NAME: aks-krishna-kiran
  AKS_NAMESPACE: java
  BACKEND_IMAGE: $(ACR_NAME).azurecr.io/backend:$(Build.BuildId)
  DEPLOYMENT_FILE: backend/backend-deployment.yaml
  DOCKER_SERVICE_CONNECTION: krishna-kiran-acr-sp-sc
  AKS_SERVICE_CONNECTION: krishan-kiran-AKS
  SERVICE_CONNECTION: krishan-kiran-sc

stages:

# Stage 1: Build & Push

- stage: Build
  displayName: 'Build and Push Docker Image'
  jobs:
  - job: BuildAndPush
    pool:
      name: kiran_agent
    steps:
    - checkout: self
#  Build Backend JAR
    - task: Maven@3
      displayName: 'Build Backend JAR'
      inputs:
        mavenPomFile: 'backend/pom.xml'
        goals: 'clean package -DskipTests=true'

#  Build and Push Docker Image to ACR
    - task: Docker@2
      displayName: 'Build and Push Backend Image to ACR'
      inputs:
        containerRegistry: '$(DOCKER_SERVICE_CONNECTION)'  # must be a Docker/ACR service connection
        repository: 'backend'
        command: 'buildAndPush'
        Dockerfile: 'backend/Dockerfile'
        buildContext: 'backend'
        tags: |
          $(Build.BuildId)


# Stage 2: Deploy to AKS

- stage: Deploy
  displayName: 'Deploy to AKS'
  dependsOn: Build
  jobs:
  - job: DeployToAKS
    pool:
      name: kiran_agent
    steps:
    - checkout: self
    - task: KubernetesManifest@1
      inputs:
        action: 'deploy'
        kubernetesServiceConnection: '$(AKS_SERVICE_CONNECTION)' # must be AKS connection
        namespace: '$(AKS_NAMESPACE)'
        manifests: '$(DEPLOYMENT_FILE)'
        containers: |
          $(ACR_NAME).azurecr.io/backend:$(Build.BuildId)