trigger: none
#  branches:
#    include:
#      - main

variables:
  BACKEND_IMAGE: myacrkrishnakiran2.azurecr.io/backend:$(Build.BuildId)
  ACR_NAME: myacrkrishnakiran2
  AKS_NAMESPACE: backend
  DEPLOYMENT_FILE: backend/backend-deployment.yaml
  AKS_RG: krishna-kiran        # Your AKS Resource Group (main RG)
  AKS_NAME: aks-krishna-kiran   # Your AKS Cluster Name (main AKS name)
  SERVICE_CONNECTION: krishan-kiran-sc # your service connection

pool:
  name: kiran_agent

steps:

# 1. Checkout Code
- checkout: self

# 2. Build Backend JAR
- script: |
    cd backend
    mvn clean package
  displayName: 'Build Backend JAR'

# 3. Azure CLI Login using Service Connection
- task: AzureCLI@2
  inputs:
    azureSubscription: $(SERVICE_CONNECTION)   # <--- Replace with your Azure DevOps service connection
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      echo "Logged in using Azure DevOps Service Connection"

# 4. Login to ACR
- task: AzureCLI@2
  inputs:
    azureSubscription: $(SERVICE_CONNECTION)
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      az acr login --name $(ACR_NAME)
  displayName: 'Login to ACR'

# 5. Build & Push Docker Image
- task: AzureCLI@2
  inputs:
    azureSubscription: $(SERVICE_CONNECTION)
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      cd backend
      docker build -t $(BACKEND_IMAGE) .
      docker push $(BACKEND_IMAGE)
  displayName: 'Build and Push Backend Docker Image'

# 6. Deploy to AKS
- task: AzureCLI@2
  inputs:
    azureSubscription: $(SERVICE_CONNECTION)
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      az aks get-credentials --resource-group $(AKS_RG) --name $(AKS_NAME)
      
      # Replace image in YAML with actual pipeline image name
      sed -i "s|myacrkrishnakiran2.azurecr.io/backend:latest|$(BACKEND_IMAGE)|g" $(DEPLOYMENT_FILE)
      echo "Updated YAML file with image: $(BACKEND_IMAGE)"
      cat $(DEPLOYMENT_FILE)

      kubectl apply -f $(DEPLOYMENT_FILE) -n $(AKS_NAMESPACE)
  displayName: 'Deploy Backend to AKS'