trigger: none
#  branches:
#    include:
#      - main

variables:
  ACR_NAME: myacrkrishnakiran2
  FRONTEND_IMAGE: $(ACR_NAME).azurecr.io/frontend:$(Build.BuildId)
  BACKEND_URL: http://your-backend-service-url

stages:
- stage: BuildAndPush
  jobs:
  - job: Frontend
    pool:
      name: kiran_agent
    steps:
    - checkout: self

    # Install Maven if not installed
    #- script: |
    #    if ! command -v mvn >/dev/null; then
    #      sudo apt-get update && sudo apt-get install -y maven
    #    fi
    #  displayName: 'Ensure Maven is Installed'

    # Build Frontend JAR
    - script: |
        cd frontend
        mvn clean package -DskipTests
      displayName: 'Build Frontend JAR'

    # Docker Login to ACR
    - task: AzureCLI@2
      inputs:
        azureSubscription: krishan-kiran-sc
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az acr login --name $(ACR_NAME)

    # Build & Push Docker Image
    - script: |
        cd frontend
        docker build --build-arg BACKEND=$BACKEND_URL -t $(FRONTEND_IMAGE) .
        docker push $(FRONTEND_IMAGE)
      displayName: 'Build and Push Frontend Docker Image'
