trigger: none

variables:
  ACR_NAME: myacrkrishnakiran2
  AKS_RG: krishna-kiran
  AKS_NAME: aks-krishna-kiran
  AKS_NAMESPACE: java
  BACKEND_IMAGE: $(ACR_NAME).azurecr.io/backend:$(Build.BuildId)
  FRONTEND_IMAGE: $(ACR_NAME).azurecr.io/frontend:$(Build.BuildId)
  DEPLOYMENT_BACKEND: backend/backend-deployment.yaml
  DEPLOYMENT_FRONTEND: frontend/frontend-deployment.yaml
  INGRESS: ingress.yaml
  DOCKER_SERVICE_CONNECTION: krishna-kiran-acr-sp-sc
  AKS_SERVICE_CONNECTION: krishan-kiran-AKS

  SONARQUBE_HOST_URL: "http://52.234.35.11:9000"
  # SONARQUBE_TOKEN: $(Sonar-Token)
  SONARQUBE_TOKEN: squ_437664680ac09398422b376153585e3d2efd5a86
  SONAR_PROJECT_KEY: "Test-Sonar-$(Build.BuildId)"
  SONAR_PROJECT_NAME: "Test-Java-Sonar-$(Build.BuildId)"

stages:

# ================= Stage 1: Build =================
- stage: Build
  displayName: 'Build Backend and Frontend JARs'
  jobs:
    - job: MavenBuild
      pool:
        name: Azure_Project_VM
      steps:
        - checkout: self
        # Build both frontend and backend
        - task: Maven@4
          displayName: 'Build All Modules (Parent POM)'
          inputs:
            mavenPomFile: 'pom.xml'      # Parent POM path
            goals: 'clean package -DskipTests=true'

        # publish the artifact
        - task: PublishBuildArtifacts@1
          displayName: 'Publish Frontend Artifact'
          inputs:
            PathtoPublish: 'frontend/target'
            ArtifactName: 'frontend-drop'
            publishLocation: 'Container'
          

        - task: PublishBuildArtifacts@1
          displayName: 'Publish Backend Artifact'
          inputs:
            PathtoPublish: 'backend/target'
            ArtifactName: 'backend-drop'
            publishLocation: 'Container'
          

        # Backend Image
        - task: Docker@2
          displayName: 'Build & Push Backend Image'
          inputs:
            containerRegistry: '$(DOCKER_SERVICE_CONNECTION)'
            repository: 'backend'
            command: 'buildAndPush'
            Dockerfile: 'backend/Dockerfile'
            buildContext: 'backend'
            # buildContext: '.'           # <-- Use repo root
            tags: |
              $(Build.BuildId)

        # Frontend Image
        - task: Docker@2
          displayName: 'Build & Push Frontend Image'
          inputs:
            containerRegistry: '$(DOCKER_SERVICE_CONNECTION)'
            repository: 'frontend'
            command: 'buildAndPush'
            Dockerfile: 'frontend/Dockerfile'
            buildContext: 'frontend'
            # buildContext: '.'           # <-- Use repo root
            tags: |
              $(Build.BuildId)

# ================= Stage 2: Deploy =================
- stage: Deploy
  displayName: 'Deploy Backend and Frontend to AKS'
  dependsOn: Build
  jobs:
    - job: DeployToAKS
      pool:
        name: Azure_Project_VM
      steps:
        - checkout: self

        - task: Kubernetes@1
          displayName: 'Test AKS Service Connection'
          inputs:
            connectionType: 'Kubernetes Service Connection'
            kubernetesServiceEndpoint: '$(AKS_SERVICE_CONNECTION)'
            command: 'kubectl'
            arguments: 'get nodes'


        # Replace backend image in manifest
        - script: |
            sed -i "s|image:.*|image: $(BACKEND_IMAGE)|" $(DEPLOYMENT_BACKEND)
          displayName: 'Update Backend Image Tag'

        # Replace frontend image in manifest
        - script: |
            sed -i "s|image:.*|image: $(FRONTEND_IMAGE)|" $(DEPLOYMENT_FRONTEND)
          displayName: 'Update Frontend Image Tag'

        # Deploy Frontend
        - task: KubernetesManifest@1
          displayName: 'Deploy Frontend to AKS'
          inputs:
            action: 'deploy'
            kubernetesServiceConnection: '$(AKS_SERVICE_CONNECTION)'
            namespace: '$(AKS_NAMESPACE)'
            manifests: '$(DEPLOYMENT_FRONTEND)'

        # Deploy Backend
        - task: KubernetesManifest@1
          displayName: 'Deploy Backend to AKS'
          inputs:
            action: 'deploy'
            kubernetesServiceConnection: '$(AKS_SERVICE_CONNECTION)'
            namespace: '$(AKS_NAMESPACE)'
            manifests: '$(DEPLOYMENT_BACKEND)'



        # Ingress Deployment (must be last)
        - task: KubernetesManifest@1
          displayName: 'Deploy Ingress'
          inputs:
            action: 'deploy'
            kubernetesServiceConnection: '$(AKS_SERVICE_CONNECTION)'
            namespace: '$(AKS_NAMESPACE)'
            manifests: '$(INGRESS)'
          
