apiVersion: v1
kind: Namespace
metadata:
  name: java
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: java
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: backend:latest 
          #image: $(BACKEND_IMAGE)   # Pipeline variable will replace this
          #image: myacrkrishnakiran2.azurecr.io/backend:latest   # Replace with your ACR image
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: java
spec:
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 80          #  external port (client/browser will use this, if you want to use LB with port 8085)
    targetPort: 8080    #  internal container port (your app runs here)
  type: ClusterIP