apiVersion: v1
kind: Namespace
metadata:
  name: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          #image: $(BACKEND_IMAGE)   # Pipeline variable will replace this
          image: myacrkrishnakiran2.azurecr.io/backend:latest   # Replace with your ACR image
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: backend
spec:
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 8085          #  external port (client/browser will use this)
    targetPort: 8080    #  internal container port (your app runs here)
  type: LoadBalancer